apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: d:\kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: moodle
  name: moodle
spec:
  ports:
  - name: "8181"
    port: 8181
    targetPort: 80
  selector:
    io.kompose.service: moodle
status:
  loadBalancer: {}
