apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: d:\kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
  - name: "6033"
    port: 6033
    targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
